### ISSUE TITLE
特性建议/请求：网页在新的标签页打开新的页面时，通过思源打开新的页面，而不是通过默认浏览器打开新的页面

### ISSUE THREAD

**Issue by otto88956** [Zuoqiu-Yingyi/siyuan-plugin-webview#10]
思源笔记版本号：2.9.4
webview版本号：v1.1.1

场景：日常有些网页中会在新的标签页中打开新的页面，网页会直接调起默认浏览器打开新的页面

特性建议/特性请求：
在网页视图插件中，网页在新的标签页打开新的页面时，通过思源打开新的页面，而不是通过默认浏览器打开新的页面

**Comment by Zuoqiu-Yingyi** [comment]
由于技术限制, 在新页面中打开超链接事件(表现为在默认浏览器中打开超链接)无法被阻止, 详情请参考: https://www.electronjs.org/docs/latest/breaking-changes#removed-webview-new-window-event
替代方案: 使用右键单击超链接以在思源新页签中打开超链接
