### ISSUE TITLE
新桌面端窗口无法使用“布局”功能

### ISSUE THREAD

**Issue by wangfh5** [Zuoqiu-Yingyi/siyuan-plugin-webview#18]
打开新桌面端窗口，然后选择某一个布局，刷新之后打开的还是原来的文档没有变化。

**Comment by Zuoqiu-Yingyi** [comment]
> 然后选择某一个布局

这里的布局功能具体是指?

**Comment by wangfh5** [comment]
<img width="396" alt="image" src="https://github.com/Zuoqiu-Yingyi/siyuan-plugin-webview/assets/51868839/3559e04b-f44f-45ef-9ac6-59ee697e03e6">

**Comment by wangfh5** [comment]
不是这个意思，是同一个布局，在原生窗口中可以打开，在插件提供的桌面端窗口中打不开，下面的录屏中左侧分屏是原生思源窗口，右侧是用此插件打开的桌面端窗口

https://github.com/Zuoqiu-Yingyi/siyuan-plugin-webview/assets/51868839/68b22cbb-69ff-43ed-88e5-def9878891c4

**Comment by Zuoqiu-Yingyi** [comment]
@wangfh5 经过我的测试, 这应该是个思源的 bug, 使用浏览器打开时布局也无法应用
