### ISSUE TITLE
无法打开设置界面

### ISSUE THREAD

**Issue by mdzz2048** [Zuoqiu-Yingyi/siyuan-plugin-webview#7]
Docker 部署，版本 v2.9.0

https://github.com/Zuoqiu-Yingyi/siyuan-plugin-webview/assets/86549958/801130f7-8df5-457b-8283-8d99326c4243

**Comment by Zuoqiu-Yingyi** [comment]
我这里 firefox (114.0.2) 与 chromium (114.0.0.0) 浏览器都能正常打开设置对话框啊👀

**Comment by mdzz2048** [comment]
思源更新到 2.9.3 Docker 部署的没有问题了。
手机伺服有这个问题，浏览器报错如下：
![image](https://github.com/Zuoqiu-Yingyi/siyuan-plugin-webview/assets/86549958/7168d576-6878-4429-87e2-3f1f5609b0a5)

**Comment by Zuoqiu-Yingyi** [comment]
> 思源更新到 2.9.3 Docker 部署的没有问题了。 手机伺服有这个问题，浏览器[firefox (114.0.2) 与 edge (114.0.1823.67) ]均报错如下： ![image](https://user-images.githubusercontent.com/86549958/250517618-7168d576-6878-4429-87e2-3f1f5609b0a5.png)

定位到问题了, 原来 crypto.randomUUID 只有在安全上下文中才能使用:heart:
REF: [Crypto.randomUUID() - Web API 接口参考 | MDN](https://developer.mozilla.org/zh-CN/docs/Web/API/Crypto/randomUUID)
